api:
  id: ""

http:
  host: "localhost"
  port: "8081"
  readtimeout: "30000"
  basepath: ""

smtp:
    host: "smtp.office365.com"
    port: "587"
    username: "mulesoftlogs@mcpher.com.au"
    password: "![0VLEZsHsThAcF2i5iRSPQ01obGZk9cFZ]"
    from: "mulesoftlogs@mcpher.com.au"